'use client'
import Head from 'next/head'
import { ReactNode } from 'react'

// ** Layouts
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'
import HomePage from 'src/views/pages/home'

// ** Pages

export default function Home() {
  return (
    <>
      <Head>
        <title>FastE</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </>
  )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
Home.guesGuard = false
Home.authGuard = false
